### ISSUE TITLE
qlop dropped '-g' parameter -- used in 10-title.sh

### ISSUE THREAD

**Issue by mouacyk** [vaeth/portage-bashrc-mv#12]
The output from qlop is mangled and prevents binary package installs.  Here's a pastebin of the emerge log and temp/environment file:

https://pastebin.com/tHy3q2c6

**Comment by vaeth** [comment]
Thanks for the report. Should be fixed in v17.0.

**Comment by mouacyk** [comment]
Thanks for making the parameter update.  However, there is another issue now with how $hour is derived.

```
linux$ qlop -tCM -- "dev-lang/perl" | sed -e 's/.* \(\d.*\)*/\1/;q'
dev-lang/perl: 4
```
That output causes a division by zero error when the $hour calculation executes:
`hour=$(( $sec / 3600 ))`

I modified it to the following, which works for me:
`qlop -tCM -- "dev-lang/perl" | tail -n 1 | sed -e 's/.* \(\d.*\)*/\1/;q' | cut -d" " -f2`

**Comment by vaeth** [comment]
Yeah, I was too tired yesterday to write a correct sed regexp. It is full of mistakes: The last * was supposed to be $, I added a wrong . after \d, and moreover, I forgot that \d is non-sed. I am still tired, but hopefully the fix works now anyway...

**Comment by mouacyk** [comment]
Thank you.

**Comment by lkraav** [comment]
Curious, is there a lightweight solution to having some binpkgs now having stored `qlop -g` calls and some not, but needing to install both at the same time?

It's almost like I would need `/usr/local/bin/qlop` to strip `-g` parameter for safety, then pass remaining cmdline to `/usr/bin/qlop`. Is there perhaps a simpler "just works" method?

**Comment by vaeth** [comment]
Sorry, I don't have a good solution to the binpkgs problem:
Portage builds the whole environment into the binpkgs, and unless you hack the binpkg manually, there is no way to modify it.

The only trick would be to put in /etc/portage/package.cflags:
```
*/* 'qlop() { :; }'
```
Unfortunately, this does not work either, because QLopSetup is executed before FlagSetup; perhaps I should have chosen the opposite order.
