### ISSUE TITLE
more cflags for clang blacklist

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/portage-bashrc-mv#2]
I found that clang does not recognize these flags too

```
-fipa-pta
-fisolate-erroneous-paths-attribute
-fsched-stalled-insns-dep
-fsched-pressure
-fsched-spec-load
-fsched-spec-load-dangerous
-fsched-stalled-insns
```

More flags can be found here

https://github.com/CyanogenMod/android_build/pull/30/files#diff-0e3c33985fa7ce9825747becb552b5e0R76

Can these flags be added to the list?

**Comment by vaeth** [comment]
Should be fixed now. Closing
