### ISSUE TITLE
Shouldn't remove la files from dev-util/colm

### ISSUE THREAD

**Issue by kepstin** [vaeth/portage-bashrc-mv#26]
The build system for dev-util/ragel currently relies on the presence of the la file from dev-util/colm; if it's not present, a build failure will result.

Gentoo bugs: https://bugs.gentoo.org/766716 and https://bugs.gentoo.org/766210

**Comment by vaeth** [comment]
Removing .la files is a sane default.
If you want/have to change this for a particular package, you can set NOLAFILEREMOVE=1, e.g. in /etc/portage/package.cflags
