### ISSUE TITLE
{+, -}'{VARIABLE}' has no effect in /etc/portage/package.cflags

### ISSUE THREAD

**Issue by blackteahamburger** [vaeth/portage-bashrc-mv#35]
` /etc/portage/make.conf`:
```
source /etc/portage/make.conf.lto.defines

CFLAGS="-march=native -Ofast ${GRAPHITE} ${DEVIRTLTO} ${IPAPTA} ${SEMINTERPOS} ${FLTO} -fuse-linker-plugin -pipe"
CXXFLAGS="${CFLAGS}"
LDFLAGS="${LDFLAGS} -fuse-ld=mold"
...
```

`/etc/portage/make.conf.lto.defines`:
```
FLTO="-flto=${NTHREADS}"
GRAPHITE="-fgraphite-identity -floop-nest-optimize"
IPAPTA="-fipa-pta"
SEMINTERPOS="-fno-semantic-interposition"
DEVIRTLTO="-fdevirtualize-at-ltrans"
```

`/etc/portage/package.cflags/plasma-systemmonitor.conf`:
```
kde-plasma/plasma-systemmonitor +'${DEVIRTLTO}'
```

After emerging kde-plasma/plasma-systemmonitor with above:

`emerge --info kde-plasma/plasma-systemmonitor`:
```
kde-plasma/plasma-systemmonitor-5.27.10::gentoo was built with the following:
USE="-debug"
CFLAGS="-march=native -Ofast -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
CXXFLAGS="-march=native -Ofast -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -fuse-ld=mold -march=native -Ofast -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe"
```

`-fdevirtualize-at-ltrans` is not removed. `+"${DEVIRTLTO}"` also has no effect.

Things get even weirder when there are multiple variables within quotes. After emerging with `kde-plasma/plasma-systemmonitor +'${DEVIRTLTO} ${GRAPHITE} ${IPAPTA}'`, `emerge --info kde-plasma/plasma-systemmonitor`:
```
kde-plasma/plasma-systemmonitor-5.27.10::gentoo was built with the following:
USE="-debug"
CFLAGS="-march=native -Ofast -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
CXXFLAGS="-march=native -Ofast -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -fuse-ld=mold -march=native -Ofast -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe"
```

Only the first option (in this case is `-fdevirtualize-at-ltrans`) is not removed.

However, `*FLAGS-=` works well. With `kde-plasma/plasma-systemmonitor *FLAGS-='${DEVIRTLTO} ${GRAPHITE} ${IPAPTA}'`, `emerge --info kde-plasma/plasma-systemmonitor`:
```
kde-plasma/plasma-systemmonitor-5.27.10::gentoo was built with the following:
USE="-debug"
CFLAGS="-march=native -Ofast -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
CXXFLAGS="-march=native -Ofast -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -fuse-ld=mold -march=native -Ofast -fno-semantic-interposition -flto=auto -fuse-linker-plugin -pipe"
```

I think this should be a bug.

**Comment by vaeth** [comment]
Note that `+-fdevirtualize-at-ltrans` removes the flag `--fdevirtualize-at-ltrans` (with two `-` signs). So this is working as intended. What is not working as intended is that `+` actually breaks at spaces and thus can be misused to unset more than one variable. However, this is a side effect that the (limited) shell capabilities are (mis)used to handle the parsing and quoting and is hard to avoid - fixing this would break other things and existing usages, so I try to avoid fixing it.

As a “workaround” you can probably misuse this bug to achieve what you want by adding a space in front of the variable.

**Comment by blackteahamburger** [comment]
Thank you for your explanation!
